[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.3",
    "fastapi>=0.129.0",
    "playwright>=1.58.0",
    "playwright-stealth>=2.0.1",
    "uvicorn>=0.40.0",
]
