[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "playwright>=1.58.0",
    "playwright-stealth>=2.0.1",
]
